# Generated by Django 4.2.6 on 2023-11-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer_app', '0002_filetransfer_shared_with_filetransfer_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='encrypted_file',
            field=models.FileField(blank=True, null=True, upload_to='encrypted_files/'),
        ),
    ]
