# Generated by Django 4.2.6 on 2023-11-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer_app', '0003_filetransfer_encrypted_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetransfer',
            name='encrypted_file',
        ),
    ]
